# Generated by Django 3.2.16 on 2022-10-26 10:08

from django.db import migrations, models
import django.db.models.deletion

import pgpartition


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partition",
            fields=[
                ("created_at", models.DateTimeField(primary_key=True, serialize=False)),
                ("int_field", models.IntegerField()),
            ],
            options={
                "partition": pgpartition.Partition(key=["created_at"], method="RANGE"),
            },
        ),
        migrations.CreateModel(
            name="PartitionFK",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "partition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tests.partition"
                    ),
                ),
            ],
        ),
    ]
