# Generated by Django 3.2.16 on 2022-10-31 07:57

from django.db import migrations, models
import pgpartition


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'partition': pgpartition.Partition(control=['id'], interval=1000, key=['id'], method='RANGE', premake=None, start_partition=None),
            },
        ),
    ]
